version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
        - image: skycomandor/doctor:1.5
    working_directory: ~/healthtel
    steps:
      - checkout
      - setup_remote_docker

      - run:
         name: clean UI
         command: ./gradlew dropUi

      - run:
          name: install npm
          command: ./gradlew installNpm

      - run:
          name: build UI
          command: ./gradlew buildUi

      - run:
          name: copy UI
          command: ./gradlew copyUi

      - run:
          name: build jar
          command: ./gradlew build

      - run:
          name: build image
          command: docker build -t skycomandor/healthtel:1.0 .

      - run:
          name: push image
          command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker push skycomandor/healthtel:1.0
      - run:
          name: Deploy
          command: |
            echo $AWS_KEY >> key.pem
            echo $AWS_KEY
            chmod 400 key.pem
            yes | ssh -i key.pem ec2-user@ec2-18-185-2-217.eu-central-1.compute.amazonaws.com "/home/ec2-user/run_container.sh"



