version: 2
jobs:
  build:
    docker:
        - image: skycomandor/doctor:1.2
    working_directory: ~/healthtel
    steps:
      - checkout

      - run:
         name: clean UI
         command: ./gradlew dropUi

      - run:
          name: build UI
          command: ./gradlew buildUi

      - run:
          name: copy UI
          command: ./gradlew copyUi
