version: 2
jobs:
  build:
    docker:
        - image: circleci/openjdk:8u232
    working_directory: ~/healthtel
    steps:
      - checkout

      - run:
         name: echo say hello
         command: echo Hello