version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
        - image: skycomandor/doctor:1.4
    working_directory: ~/healthtel
    steps:
      - checkout

      - run:
         name: clean UI
         command: ./gradlew dropUi

      - run:
          name: install npm
          command: ./gradlew installNpm

      - run:
          name: build UI
          command: ./gradlew buildUi

      - run:
          name: copy UI
          command: ./gradlew copyUi

      - run:
          name: build jar
          command: ./gradlew jar

      - run:
          name: build image
          command: docker build -t skycomandor/healthtel:1.0 . \
          docker login -u "$DOCKER_USER" -p "DOCKER_PASSWORD" \
          docker push skycomandor/healthtel:1.0 \
