version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
        - image: skycomandor/doctor:1.4
    working_directory: ~/healthtel
    steps:
      - checkout

      - run:
         name: clean UI
         command: ./gradlew dropUi

      - run:
          name: install npm
          command: ./gradlew installNpm

      - run:
          name: build UI
          command: ./gradlew buildUi

      - run:
          name: copy UI
          command: ./gradlew copyUi


